services:
  db:
    image: postgres
    restart: always
    container_name: usd_uah_rate_api_db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=postgres
    ports:
      - '5444:5432'
    volumes:
      - db:/var/lib/postgresql/data
  server:
    build:
      context: .
      target: development
    environment:
      NODE_ENV: production
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 8080:8080

volumes:
  db:
    driver: local
